# ================= General attack params =================
use_vel: True
use_k: True

fix_t: -1
target_id: -1

iters: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
eps: 1.0
step_size: 5.0e-3
step_size_dds: 1.0e-2
step_size_dh: 1.0e-3
collision_reg: 0.0
motion_reg: 0

exp_name: base

debug: False
